// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpSLW0lAihkd6URIr0-hA8nOPLBtcXn4w',
    appId: '1:209466685782:web:10b0b1682b3f8fd641bef7',
    messagingSenderId: '209466685782',
    projectId: 'moviefreak-4324d',
    authDomain: 'moviefreak-4324d.firebaseapp.com',
    storageBucket: 'moviefreak-4324d.appspot.com',
    measurementId: 'G-BTPEYCTDBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcCQO2CvbgO_FLlCj6p9o9M3gejUhaY0k',
    appId: '1:209466685782:android:ed9bca9c21b393b841bef7',
    messagingSenderId: '209466685782',
    projectId: 'moviefreak-4324d',
    storageBucket: 'moviefreak-4324d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP7yssCzlqgjT00ZPn8iJEwYaIvYWtGLI',
    appId: '1:209466685782:ios:9f5aaa4ba3365fd541bef7',
    messagingSenderId: '209466685782',
    projectId: 'moviefreak-4324d',
    storageBucket: 'moviefreak-4324d.appspot.com',
    iosClientId: '209466685782-uf76hmkmo68iftbn84tbrfn684r6rser.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviefreak',
  );
}
